################################################################################
# Automatically-generated file. Do not edit!
################################################################################

OBJ_SRCS := 
ASM_SRCS := 
C_SRCS := 
O_SRCS := 
S_UPPER_SRCS := 
EXECUTABLES := 
OBJS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
build/install/lib \
build/userland/bin/cat \
build/userland/bin/cp \
build/userland/bin/false \
build/userland/bin/ln \
build/userland/bin/ls \
build/userland/bin/mkdir \
build/userland/bin/mv \
build/userland/bin/pwd \
build/userland/bin/rm \
build/userland/bin/rmdir \
build/userland/bin/sh \
build/userland/bin/sync \
build/userland/bin/tac \
build/userland/bin/true \
build/userland/lib/crt0 \
build/userland/lib/libc \
build/userland/lib/libtest \
build/userland/lib/libtest161 \
build/userland/sbin/dumpsfs \
build/userland/sbin/halt \
build/userland/sbin/mksfs \
build/userland/sbin/poweroff \
build/userland/sbin/reboot \
build/userland/sbin/sfsck \
build/userland/testbin/add \
build/userland/testbin/argtest \
build/userland/testbin/badcall \
build/userland/testbin/bigexec \
build/userland/testbin/bigfile \
build/userland/testbin/bigfork \
build/userland/testbin/bigseek \
build/userland/testbin/bloat \
build/userland/testbin/closetest \
build/userland/testbin/conman \
build/userland/testbin/consoletest \
build/userland/testbin/crash \
build/userland/testbin/ctest \
build/userland/testbin/dirconc \
build/userland/testbin/dirseek \
build/userland/testbin/dirtest \
build/userland/testbin/f_test \
build/userland/testbin/factorial \
build/userland/testbin/farm \
build/userland/testbin/faulter \
build/userland/testbin/fileonlytest \
build/userland/testbin/filetest \
build/userland/testbin/forkbomb \
build/userland/testbin/forktest \
build/userland/testbin/frack \
build/userland/testbin/guzzle \
build/userland/testbin/hash \
build/userland/testbin/hog \
build/userland/testbin/huge \
build/userland/testbin/kitchen \
build/userland/testbin/malloctest \
build/userland/testbin/matmult \
build/userland/testbin/multiexec \
build/userland/testbin/opentest \
build/userland/testbin/palin \
build/userland/testbin/parallelvm \
build/userland/testbin/poisondisk \
build/userland/testbin/psort \
build/userland/testbin/quinthuge \
build/userland/testbin/quintmat \
build/userland/testbin/quintsort \
build/userland/testbin/randcall \
build/userland/testbin/readwritetest \
build/userland/testbin/redirect \
build/userland/testbin/rmdirtest \
build/userland/testbin/rmtest \
build/userland/testbin/sbrktest \
build/userland/testbin/schedpong \
build/userland/testbin/shelltest \
build/userland/testbin/shll \
build/userland/testbin/sink \
build/userland/testbin/sort \
build/userland/testbin/sparsefile \
build/userland/testbin/spinner \
build/userland/testbin/stacktest \
build/userland/testbin/sty \
build/userland/testbin/tail \
build/userland/testbin/tictac \
build/userland/testbin/triplehuge \
build/userland/testbin/triplemat \
build/userland/testbin/triplesort \
build/userland/testbin/usemtest \
build/userland/testbin/waiter \
build/userland/testbin/zero \
common/gcc-millicode \
common/libc/arch/mips \
common/libc/printf \
common/libc/stdlib \
common/libc/string \
common/libtest161 \
kern/arch/mips/locore \
kern/arch/mips/syscall \
kern/arch/mips/thread \
kern/arch/mips/vm \
kern/arch/sys161/dev \
kern/arch/sys161/main \
kern/compile/ASST2 \
kern/compile/ASST3 \
kern/compile/DUMBVM \
kern/dev/generic \
kern/dev/lamebus \
kern/fs/semfs \
kern/fs/sfs \
kern/lib \
kern/main \
kern/proc \
kern/synchprobs \
kern/syscall \
kern/test \
kern/thread \
kern/vfs \
kern/vm \
userland/bin/cat \
userland/bin/cp \
userland/bin/false \
userland/bin/ln \
userland/bin/ls \
userland/bin/mkdir \
userland/bin/mv \
userland/bin/pwd \
userland/bin/rm \
userland/bin/rmdir \
userland/bin/sh \
userland/bin/sync \
userland/bin/tac \
userland/bin/true \
userland/lib/crt0/mips \
userland/lib/hostcompat \
userland/lib/libc/arch/mips \
userland/lib/libc/stdio \
userland/lib/libc/stdlib \
userland/lib/libc/string \
userland/lib/libc/time \
userland/lib/libc/unix \
userland/lib/libtest \
userland/sbin/dumpsfs \
userland/sbin/halt \
userland/sbin/mksfs \
userland/sbin/poweroff \
userland/sbin/reboot \
userland/sbin/sfsck \
userland/testbin/add \
userland/testbin/argtest \
userland/testbin/badcall \
userland/testbin/bigexec \
userland/testbin/bigfile \
userland/testbin/bigfork \
userland/testbin/bigseek \
userland/testbin/bloat \
userland/testbin/closetest \
userland/testbin/conman \
userland/testbin/consoletest \
userland/testbin/crash \
userland/testbin/ctest \
userland/testbin/dirconc \
userland/testbin/dirseek \
userland/testbin/dirtest \
userland/testbin/f_test \
userland/testbin/factorial \
userland/testbin/farm \
userland/testbin/faulter \
userland/testbin/fileonlytest \
userland/testbin/filetest \
userland/testbin/forkbomb \
userland/testbin/forktest \
userland/testbin/frack \
userland/testbin/guzzle \
userland/testbin/hash \
userland/testbin/hog \
userland/testbin/huge \
userland/testbin/kitchen \
userland/testbin/malloctest \
userland/testbin/matmult \
userland/testbin/multiexec \
userland/testbin/opentest \
userland/testbin/palin \
userland/testbin/parallelvm \
userland/testbin/poisondisk \
userland/testbin/psort \
userland/testbin/quinthuge \
userland/testbin/quintmat \
userland/testbin/quintsort \
userland/testbin/randcall \
userland/testbin/readwritetest \
userland/testbin/redirect \
userland/testbin/rmdirtest \
userland/testbin/rmtest \
userland/testbin/sbrktest \
userland/testbin/schedpong \
userland/testbin/shelltest \
userland/testbin/shll \
userland/testbin/sink \
userland/testbin/sort \
userland/testbin/sparsefile \
userland/testbin/spinner \
userland/testbin/stacktest \
userland/testbin/sty \
userland/testbin/tail \
userland/testbin/tictac \
userland/testbin/triplehuge \
userland/testbin/triplemat \
userland/testbin/triplesort \
userland/testbin/usemtest \
userland/testbin/userthreads \
userland/testbin/waiter \
userland/testbin/zero \

