################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../kern/compile/DUMBVM/.depend.__printf.c \
../kern/compile/DUMBVM/.depend.adddi3.c \
../kern/compile/DUMBVM/.depend.anddi3.c \
../kern/compile/DUMBVM/.depend.array.c \
../kern/compile/DUMBVM/.depend.arraytest.c \
../kern/compile/DUMBVM/.depend.ashldi3.c \
../kern/compile/DUMBVM/.depend.ashrdi3.c \
../kern/compile/DUMBVM/.depend.atoi.c \
../kern/compile/DUMBVM/.depend.autoconf.c \
../kern/compile/DUMBVM/.depend.beep.c \
../kern/compile/DUMBVM/.depend.beep_ltimer.c \
../kern/compile/DUMBVM/.depend.bitmap.c \
../kern/compile/DUMBVM/.depend.bitmaptest.c \
../kern/compile/DUMBVM/.depend.bswap.c \
../kern/compile/DUMBVM/.depend.bzero.c \
../kern/compile/DUMBVM/.depend.clock.c \
../kern/compile/DUMBVM/.depend.cmpdi2.c \
../kern/compile/DUMBVM/.depend.con_lser.c \
../kern/compile/DUMBVM/.depend.console.c \
../kern/compile/DUMBVM/.depend.copyinout.c \
../kern/compile/DUMBVM/.depend.cpu.c \
../kern/compile/DUMBVM/.depend.device.c \
../kern/compile/DUMBVM/.depend.devnull.c \
../kern/compile/DUMBVM/.depend.divdi3.c \
../kern/compile/DUMBVM/.depend.dumbvm.c \
../kern/compile/DUMBVM/.depend.emu.c \
../kern/compile/DUMBVM/.depend.emu_att.c \
../kern/compile/DUMBVM/.depend.fstest.c \
../kern/compile/DUMBVM/.depend.hmacunit.c \
../kern/compile/DUMBVM/.depend.iordi3.c \
../kern/compile/DUMBVM/.depend.kgets.c \
../kern/compile/DUMBVM/.depend.kmalloc.c \
../kern/compile/DUMBVM/.depend.kmalloctest.c \
../kern/compile/DUMBVM/.depend.kprintf.c \
../kern/compile/DUMBVM/.depend.lamebus.c \
../kern/compile/DUMBVM/.depend.lamebus_machdep.c \
../kern/compile/DUMBVM/.depend.lhd.c \
../kern/compile/DUMBVM/.depend.lhd_att.c \
../kern/compile/DUMBVM/.depend.lib.c \
../kern/compile/DUMBVM/.depend.loadelf.c \
../kern/compile/DUMBVM/.depend.lrandom.c \
../kern/compile/DUMBVM/.depend.lrandom_att.c \
../kern/compile/DUMBVM/.depend.lser.c \
../kern/compile/DUMBVM/.depend.lser_att.c \
../kern/compile/DUMBVM/.depend.lshldi3.c \
../kern/compile/DUMBVM/.depend.lshrdi3.c \
../kern/compile/DUMBVM/.depend.ltimer.c \
../kern/compile/DUMBVM/.depend.ltimer_att.c \
../kern/compile/DUMBVM/.depend.ltrace.c \
../kern/compile/DUMBVM/.depend.ltrace_att.c \
../kern/compile/DUMBVM/.depend.main.c \
../kern/compile/DUMBVM/.depend.memcpy.c \
../kern/compile/DUMBVM/.depend.memmove.c \
../kern/compile/DUMBVM/.depend.memset.c \
../kern/compile/DUMBVM/.depend.menu.c \
../kern/compile/DUMBVM/.depend.misc.c \
../kern/compile/DUMBVM/.depend.moddi3.c \
../kern/compile/DUMBVM/.depend.muldi3.c \
../kern/compile/DUMBVM/.depend.negdi2.c \
../kern/compile/DUMBVM/.depend.notdi2.c \
../kern/compile/DUMBVM/.depend.proc.c \
../kern/compile/DUMBVM/.depend.qdivrem.c \
../kern/compile/DUMBVM/.depend.ram.c \
../kern/compile/DUMBVM/.depend.random.c \
../kern/compile/DUMBVM/.depend.random_lrandom.c \
../kern/compile/DUMBVM/.depend.rtclock.c \
../kern/compile/DUMBVM/.depend.rtclock_ltimer.c \
../kern/compile/DUMBVM/.depend.runprogram.c \
../kern/compile/DUMBVM/.depend.rwtest.c \
../kern/compile/DUMBVM/.depend.secure.c \
../kern/compile/DUMBVM/.depend.semfs_fsops.c \
../kern/compile/DUMBVM/.depend.semfs_obj.c \
../kern/compile/DUMBVM/.depend.semfs_vnops.c \
../kern/compile/DUMBVM/.depend.semunit.c \
../kern/compile/DUMBVM/.depend.sfs_balloc.c \
../kern/compile/DUMBVM/.depend.sfs_bmap.c \
../kern/compile/DUMBVM/.depend.sfs_dir.c \
../kern/compile/DUMBVM/.depend.sfs_fsops.c \
../kern/compile/DUMBVM/.depend.sfs_inode.c \
../kern/compile/DUMBVM/.depend.sfs_io.c \
../kern/compile/DUMBVM/.depend.sfs_vnops.c \
../kern/compile/DUMBVM/.depend.sha256.c \
../kern/compile/DUMBVM/.depend.snprintf.c \
../kern/compile/DUMBVM/.depend.spinlock.c \
../kern/compile/DUMBVM/.depend.spl.c \
../kern/compile/DUMBVM/.depend.strcat.c \
../kern/compile/DUMBVM/.depend.strchr.c \
../kern/compile/DUMBVM/.depend.strcmp.c \
../kern/compile/DUMBVM/.depend.strcpy.c \
../kern/compile/DUMBVM/.depend.strlen.c \
../kern/compile/DUMBVM/.depend.strrchr.c \
../kern/compile/DUMBVM/.depend.strtok_r.c \
../kern/compile/DUMBVM/.depend.subdi3.c \
../kern/compile/DUMBVM/.depend.switchframe.c \
../kern/compile/DUMBVM/.depend.synch.c \
../kern/compile/DUMBVM/.depend.synchtest.c \
../kern/compile/DUMBVM/.depend.syscall.c \
../kern/compile/DUMBVM/.depend.test161.c \
../kern/compile/DUMBVM/.depend.thread.c \
../kern/compile/DUMBVM/.depend.thread_machdep.c \
../kern/compile/DUMBVM/.depend.threadlist.c \
../kern/compile/DUMBVM/.depend.threadlisttest.c \
../kern/compile/DUMBVM/.depend.threadtest.c \
../kern/compile/DUMBVM/.depend.time.c \
../kern/compile/DUMBVM/.depend.time_syscalls.c \
../kern/compile/DUMBVM/.depend.trap.c \
../kern/compile/DUMBVM/.depend.tt3.c \
../kern/compile/DUMBVM/.depend.ucmpdi2.c \
../kern/compile/DUMBVM/.depend.udivdi3.c \
../kern/compile/DUMBVM/.depend.uio.c \
../kern/compile/DUMBVM/.depend.umoddi3.c \
../kern/compile/DUMBVM/.depend.vfscwd.c \
../kern/compile/DUMBVM/.depend.vfsfail.c \
../kern/compile/DUMBVM/.depend.vfslist.c \
../kern/compile/DUMBVM/.depend.vfslookup.c \
../kern/compile/DUMBVM/.depend.vfspath.c \
../kern/compile/DUMBVM/.depend.vnode.c \
../kern/compile/DUMBVM/.depend.xordi3.c \
../kern/compile/DUMBVM/autoconf.c \
../kern/compile/DUMBVM/vers.c 

O_SRCS += \
../kern/compile/DUMBVM/__printf.o \
../kern/compile/DUMBVM/adddi3.o \
../kern/compile/DUMBVM/anddi3.o \
../kern/compile/DUMBVM/array.o \
../kern/compile/DUMBVM/arraytest.o \
../kern/compile/DUMBVM/ashldi3.o \
../kern/compile/DUMBVM/ashrdi3.o \
../kern/compile/DUMBVM/atoi.o \
../kern/compile/DUMBVM/autoconf.o \
../kern/compile/DUMBVM/beep.o \
../kern/compile/DUMBVM/beep_ltimer.o \
../kern/compile/DUMBVM/bitmap.o \
../kern/compile/DUMBVM/bitmaptest.o \
../kern/compile/DUMBVM/bswap.o \
../kern/compile/DUMBVM/bzero.o \
../kern/compile/DUMBVM/cache-mips161.o \
../kern/compile/DUMBVM/clock.o \
../kern/compile/DUMBVM/cmpdi2.o \
../kern/compile/DUMBVM/con_lser.o \
../kern/compile/DUMBVM/console.o \
../kern/compile/DUMBVM/copyinout.o \
../kern/compile/DUMBVM/cpu.o \
../kern/compile/DUMBVM/device.o \
../kern/compile/DUMBVM/devnull.o \
../kern/compile/DUMBVM/divdi3.o \
../kern/compile/DUMBVM/dumbvm.o \
../kern/compile/DUMBVM/emu.o \
../kern/compile/DUMBVM/emu_att.o \
../kern/compile/DUMBVM/exception-mips1.o \
../kern/compile/DUMBVM/fstest.o \
../kern/compile/DUMBVM/hmacunit.o \
../kern/compile/DUMBVM/iordi3.o \
../kern/compile/DUMBVM/kgets.o \
../kern/compile/DUMBVM/kmalloc.o \
../kern/compile/DUMBVM/kmalloctest.o \
../kern/compile/DUMBVM/kprintf.o \
../kern/compile/DUMBVM/lamebus.o \
../kern/compile/DUMBVM/lamebus_machdep.o \
../kern/compile/DUMBVM/lhd.o \
../kern/compile/DUMBVM/lhd_att.o \
../kern/compile/DUMBVM/lib.o \
../kern/compile/DUMBVM/loadelf.o \
../kern/compile/DUMBVM/lrandom.o \
../kern/compile/DUMBVM/lrandom_att.o \
../kern/compile/DUMBVM/lser.o \
../kern/compile/DUMBVM/lser_att.o \
../kern/compile/DUMBVM/lshldi3.o \
../kern/compile/DUMBVM/lshrdi3.o \
../kern/compile/DUMBVM/ltimer.o \
../kern/compile/DUMBVM/ltimer_att.o \
../kern/compile/DUMBVM/ltrace.o \
../kern/compile/DUMBVM/ltrace_att.o \
../kern/compile/DUMBVM/main.o \
../kern/compile/DUMBVM/memcpy.o \
../kern/compile/DUMBVM/memmove.o \
../kern/compile/DUMBVM/memset.o \
../kern/compile/DUMBVM/menu.o \
../kern/compile/DUMBVM/misc.o \
../kern/compile/DUMBVM/moddi3.o \
../kern/compile/DUMBVM/muldi3.o \
../kern/compile/DUMBVM/negdi2.o \
../kern/compile/DUMBVM/notdi2.o \
../kern/compile/DUMBVM/proc.o \
../kern/compile/DUMBVM/qdivrem.o \
../kern/compile/DUMBVM/ram.o \
../kern/compile/DUMBVM/random.o \
../kern/compile/DUMBVM/random_lrandom.o \
../kern/compile/DUMBVM/rtclock.o \
../kern/compile/DUMBVM/rtclock_ltimer.o \
../kern/compile/DUMBVM/runprogram.o \
../kern/compile/DUMBVM/rwtest.o \
../kern/compile/DUMBVM/secure.o \
../kern/compile/DUMBVM/semfs_fsops.o \
../kern/compile/DUMBVM/semfs_obj.o \
../kern/compile/DUMBVM/semfs_vnops.o \
../kern/compile/DUMBVM/semunit.o \
../kern/compile/DUMBVM/setjmp.o \
../kern/compile/DUMBVM/sfs_balloc.o \
../kern/compile/DUMBVM/sfs_bmap.o \
../kern/compile/DUMBVM/sfs_dir.o \
../kern/compile/DUMBVM/sfs_fsops.o \
../kern/compile/DUMBVM/sfs_inode.o \
../kern/compile/DUMBVM/sfs_io.o \
../kern/compile/DUMBVM/sfs_vnops.o \
../kern/compile/DUMBVM/sha256.o \
../kern/compile/DUMBVM/snprintf.o \
../kern/compile/DUMBVM/spinlock.o \
../kern/compile/DUMBVM/spl.o \
../kern/compile/DUMBVM/start.o \
../kern/compile/DUMBVM/strcat.o \
../kern/compile/DUMBVM/strchr.o \
../kern/compile/DUMBVM/strcmp.o \
../kern/compile/DUMBVM/strcpy.o \
../kern/compile/DUMBVM/strlen.o \
../kern/compile/DUMBVM/strrchr.o \
../kern/compile/DUMBVM/strtok_r.o \
../kern/compile/DUMBVM/subdi3.o \
../kern/compile/DUMBVM/switch.o \
../kern/compile/DUMBVM/switchframe.o \
../kern/compile/DUMBVM/synch.o \
../kern/compile/DUMBVM/synchtest.o \
../kern/compile/DUMBVM/syscall.o \
../kern/compile/DUMBVM/test161.o \
../kern/compile/DUMBVM/thread.o \
../kern/compile/DUMBVM/thread_machdep.o \
../kern/compile/DUMBVM/threadlist.o \
../kern/compile/DUMBVM/threadlisttest.o \
../kern/compile/DUMBVM/threadstart.o \
../kern/compile/DUMBVM/threadtest.o \
../kern/compile/DUMBVM/time.o \
../kern/compile/DUMBVM/time_syscalls.o \
../kern/compile/DUMBVM/tlb-mips161.o \
../kern/compile/DUMBVM/trap.o \
../kern/compile/DUMBVM/tt3.o \
../kern/compile/DUMBVM/ucmpdi2.o \
../kern/compile/DUMBVM/udivdi3.o \
../kern/compile/DUMBVM/uio.o \
../kern/compile/DUMBVM/umoddi3.o \
../kern/compile/DUMBVM/vers.o \
../kern/compile/DUMBVM/vfscwd.o \
../kern/compile/DUMBVM/vfsfail.o \
../kern/compile/DUMBVM/vfslist.o \
../kern/compile/DUMBVM/vfslookup.o \
../kern/compile/DUMBVM/vfspath.o \
../kern/compile/DUMBVM/vnode.o \
../kern/compile/DUMBVM/xordi3.o 

S_UPPER_SRCS += \
../kern/compile/DUMBVM/.depend.cache-mips161.S \
../kern/compile/DUMBVM/.depend.exception-mips1.S \
../kern/compile/DUMBVM/.depend.setjmp.S \
../kern/compile/DUMBVM/.depend.start.S \
../kern/compile/DUMBVM/.depend.switch.S \
../kern/compile/DUMBVM/.depend.threadstart.S \
../kern/compile/DUMBVM/.depend.tlb-mips161.S 

OBJS += \
./kern/compile/DUMBVM/.depend.__printf.o \
./kern/compile/DUMBVM/.depend.adddi3.o \
./kern/compile/DUMBVM/.depend.anddi3.o \
./kern/compile/DUMBVM/.depend.array.o \
./kern/compile/DUMBVM/.depend.arraytest.o \
./kern/compile/DUMBVM/.depend.ashldi3.o \
./kern/compile/DUMBVM/.depend.ashrdi3.o \
./kern/compile/DUMBVM/.depend.atoi.o \
./kern/compile/DUMBVM/.depend.autoconf.o \
./kern/compile/DUMBVM/.depend.beep.o \
./kern/compile/DUMBVM/.depend.beep_ltimer.o \
./kern/compile/DUMBVM/.depend.bitmap.o \
./kern/compile/DUMBVM/.depend.bitmaptest.o \
./kern/compile/DUMBVM/.depend.bswap.o \
./kern/compile/DUMBVM/.depend.bzero.o \
./kern/compile/DUMBVM/.depend.cache-mips161.o \
./kern/compile/DUMBVM/.depend.clock.o \
./kern/compile/DUMBVM/.depend.cmpdi2.o \
./kern/compile/DUMBVM/.depend.con_lser.o \
./kern/compile/DUMBVM/.depend.console.o \
./kern/compile/DUMBVM/.depend.copyinout.o \
./kern/compile/DUMBVM/.depend.cpu.o \
./kern/compile/DUMBVM/.depend.device.o \
./kern/compile/DUMBVM/.depend.devnull.o \
./kern/compile/DUMBVM/.depend.divdi3.o \
./kern/compile/DUMBVM/.depend.dumbvm.o \
./kern/compile/DUMBVM/.depend.emu.o \
./kern/compile/DUMBVM/.depend.emu_att.o \
./kern/compile/DUMBVM/.depend.exception-mips1.o \
./kern/compile/DUMBVM/.depend.fstest.o \
./kern/compile/DUMBVM/.depend.hmacunit.o \
./kern/compile/DUMBVM/.depend.iordi3.o \
./kern/compile/DUMBVM/.depend.kgets.o \
./kern/compile/DUMBVM/.depend.kmalloc.o \
./kern/compile/DUMBVM/.depend.kmalloctest.o \
./kern/compile/DUMBVM/.depend.kprintf.o \
./kern/compile/DUMBVM/.depend.lamebus.o \
./kern/compile/DUMBVM/.depend.lamebus_machdep.o \
./kern/compile/DUMBVM/.depend.lhd.o \
./kern/compile/DUMBVM/.depend.lhd_att.o \
./kern/compile/DUMBVM/.depend.lib.o \
./kern/compile/DUMBVM/.depend.loadelf.o \
./kern/compile/DUMBVM/.depend.lrandom.o \
./kern/compile/DUMBVM/.depend.lrandom_att.o \
./kern/compile/DUMBVM/.depend.lser.o \
./kern/compile/DUMBVM/.depend.lser_att.o \
./kern/compile/DUMBVM/.depend.lshldi3.o \
./kern/compile/DUMBVM/.depend.lshrdi3.o \
./kern/compile/DUMBVM/.depend.ltimer.o \
./kern/compile/DUMBVM/.depend.ltimer_att.o \
./kern/compile/DUMBVM/.depend.ltrace.o \
./kern/compile/DUMBVM/.depend.ltrace_att.o \
./kern/compile/DUMBVM/.depend.main.o \
./kern/compile/DUMBVM/.depend.memcpy.o \
./kern/compile/DUMBVM/.depend.memmove.o \
./kern/compile/DUMBVM/.depend.memset.o \
./kern/compile/DUMBVM/.depend.menu.o \
./kern/compile/DUMBVM/.depend.misc.o \
./kern/compile/DUMBVM/.depend.moddi3.o \
./kern/compile/DUMBVM/.depend.muldi3.o \
./kern/compile/DUMBVM/.depend.negdi2.o \
./kern/compile/DUMBVM/.depend.notdi2.o \
./kern/compile/DUMBVM/.depend.proc.o \
./kern/compile/DUMBVM/.depend.qdivrem.o \
./kern/compile/DUMBVM/.depend.ram.o \
./kern/compile/DUMBVM/.depend.random.o \
./kern/compile/DUMBVM/.depend.random_lrandom.o \
./kern/compile/DUMBVM/.depend.rtclock.o \
./kern/compile/DUMBVM/.depend.rtclock_ltimer.o \
./kern/compile/DUMBVM/.depend.runprogram.o \
./kern/compile/DUMBVM/.depend.rwtest.o \
./kern/compile/DUMBVM/.depend.secure.o \
./kern/compile/DUMBVM/.depend.semfs_fsops.o \
./kern/compile/DUMBVM/.depend.semfs_obj.o \
./kern/compile/DUMBVM/.depend.semfs_vnops.o \
./kern/compile/DUMBVM/.depend.semunit.o \
./kern/compile/DUMBVM/.depend.setjmp.o \
./kern/compile/DUMBVM/.depend.sfs_balloc.o \
./kern/compile/DUMBVM/.depend.sfs_bmap.o \
./kern/compile/DUMBVM/.depend.sfs_dir.o \
./kern/compile/DUMBVM/.depend.sfs_fsops.o \
./kern/compile/DUMBVM/.depend.sfs_inode.o \
./kern/compile/DUMBVM/.depend.sfs_io.o \
./kern/compile/DUMBVM/.depend.sfs_vnops.o \
./kern/compile/DUMBVM/.depend.sha256.o \
./kern/compile/DUMBVM/.depend.snprintf.o \
./kern/compile/DUMBVM/.depend.spinlock.o \
./kern/compile/DUMBVM/.depend.spl.o \
./kern/compile/DUMBVM/.depend.start.o \
./kern/compile/DUMBVM/.depend.strcat.o \
./kern/compile/DUMBVM/.depend.strchr.o \
./kern/compile/DUMBVM/.depend.strcmp.o \
./kern/compile/DUMBVM/.depend.strcpy.o \
./kern/compile/DUMBVM/.depend.strlen.o \
./kern/compile/DUMBVM/.depend.strrchr.o \
./kern/compile/DUMBVM/.depend.strtok_r.o \
./kern/compile/DUMBVM/.depend.subdi3.o \
./kern/compile/DUMBVM/.depend.switch.o \
./kern/compile/DUMBVM/.depend.switchframe.o \
./kern/compile/DUMBVM/.depend.synch.o \
./kern/compile/DUMBVM/.depend.synchtest.o \
./kern/compile/DUMBVM/.depend.syscall.o \
./kern/compile/DUMBVM/.depend.test161.o \
./kern/compile/DUMBVM/.depend.thread.o \
./kern/compile/DUMBVM/.depend.thread_machdep.o \
./kern/compile/DUMBVM/.depend.threadlist.o \
./kern/compile/DUMBVM/.depend.threadlisttest.o \
./kern/compile/DUMBVM/.depend.threadstart.o \
./kern/compile/DUMBVM/.depend.threadtest.o \
./kern/compile/DUMBVM/.depend.time.o \
./kern/compile/DUMBVM/.depend.time_syscalls.o \
./kern/compile/DUMBVM/.depend.tlb-mips161.o \
./kern/compile/DUMBVM/.depend.trap.o \
./kern/compile/DUMBVM/.depend.tt3.o \
./kern/compile/DUMBVM/.depend.ucmpdi2.o \
./kern/compile/DUMBVM/.depend.udivdi3.o \
./kern/compile/DUMBVM/.depend.uio.o \
./kern/compile/DUMBVM/.depend.umoddi3.o \
./kern/compile/DUMBVM/.depend.vfscwd.o \
./kern/compile/DUMBVM/.depend.vfsfail.o \
./kern/compile/DUMBVM/.depend.vfslist.o \
./kern/compile/DUMBVM/.depend.vfslookup.o \
./kern/compile/DUMBVM/.depend.vfspath.o \
./kern/compile/DUMBVM/.depend.vnode.o \
./kern/compile/DUMBVM/.depend.xordi3.o \
./kern/compile/DUMBVM/autoconf.o \
./kern/compile/DUMBVM/vers.o 

C_DEPS += \
./kern/compile/DUMBVM/.depend.__printf.d \
./kern/compile/DUMBVM/.depend.adddi3.d \
./kern/compile/DUMBVM/.depend.anddi3.d \
./kern/compile/DUMBVM/.depend.array.d \
./kern/compile/DUMBVM/.depend.arraytest.d \
./kern/compile/DUMBVM/.depend.ashldi3.d \
./kern/compile/DUMBVM/.depend.ashrdi3.d \
./kern/compile/DUMBVM/.depend.atoi.d \
./kern/compile/DUMBVM/.depend.autoconf.d \
./kern/compile/DUMBVM/.depend.beep.d \
./kern/compile/DUMBVM/.depend.beep_ltimer.d \
./kern/compile/DUMBVM/.depend.bitmap.d \
./kern/compile/DUMBVM/.depend.bitmaptest.d \
./kern/compile/DUMBVM/.depend.bswap.d \
./kern/compile/DUMBVM/.depend.bzero.d \
./kern/compile/DUMBVM/.depend.clock.d \
./kern/compile/DUMBVM/.depend.cmpdi2.d \
./kern/compile/DUMBVM/.depend.con_lser.d \
./kern/compile/DUMBVM/.depend.console.d \
./kern/compile/DUMBVM/.depend.copyinout.d \
./kern/compile/DUMBVM/.depend.cpu.d \
./kern/compile/DUMBVM/.depend.device.d \
./kern/compile/DUMBVM/.depend.devnull.d \
./kern/compile/DUMBVM/.depend.divdi3.d \
./kern/compile/DUMBVM/.depend.dumbvm.d \
./kern/compile/DUMBVM/.depend.emu.d \
./kern/compile/DUMBVM/.depend.emu_att.d \
./kern/compile/DUMBVM/.depend.fstest.d \
./kern/compile/DUMBVM/.depend.hmacunit.d \
./kern/compile/DUMBVM/.depend.iordi3.d \
./kern/compile/DUMBVM/.depend.kgets.d \
./kern/compile/DUMBVM/.depend.kmalloc.d \
./kern/compile/DUMBVM/.depend.kmalloctest.d \
./kern/compile/DUMBVM/.depend.kprintf.d \
./kern/compile/DUMBVM/.depend.lamebus.d \
./kern/compile/DUMBVM/.depend.lamebus_machdep.d \
./kern/compile/DUMBVM/.depend.lhd.d \
./kern/compile/DUMBVM/.depend.lhd_att.d \
./kern/compile/DUMBVM/.depend.lib.d \
./kern/compile/DUMBVM/.depend.loadelf.d \
./kern/compile/DUMBVM/.depend.lrandom.d \
./kern/compile/DUMBVM/.depend.lrandom_att.d \
./kern/compile/DUMBVM/.depend.lser.d \
./kern/compile/DUMBVM/.depend.lser_att.d \
./kern/compile/DUMBVM/.depend.lshldi3.d \
./kern/compile/DUMBVM/.depend.lshrdi3.d \
./kern/compile/DUMBVM/.depend.ltimer.d \
./kern/compile/DUMBVM/.depend.ltimer_att.d \
./kern/compile/DUMBVM/.depend.ltrace.d \
./kern/compile/DUMBVM/.depend.ltrace_att.d \
./kern/compile/DUMBVM/.depend.main.d \
./kern/compile/DUMBVM/.depend.memcpy.d \
./kern/compile/DUMBVM/.depend.memmove.d \
./kern/compile/DUMBVM/.depend.memset.d \
./kern/compile/DUMBVM/.depend.menu.d \
./kern/compile/DUMBVM/.depend.misc.d \
./kern/compile/DUMBVM/.depend.moddi3.d \
./kern/compile/DUMBVM/.depend.muldi3.d \
./kern/compile/DUMBVM/.depend.negdi2.d \
./kern/compile/DUMBVM/.depend.notdi2.d \
./kern/compile/DUMBVM/.depend.proc.d \
./kern/compile/DUMBVM/.depend.qdivrem.d \
./kern/compile/DUMBVM/.depend.ram.d \
./kern/compile/DUMBVM/.depend.random.d \
./kern/compile/DUMBVM/.depend.random_lrandom.d \
./kern/compile/DUMBVM/.depend.rtclock.d \
./kern/compile/DUMBVM/.depend.rtclock_ltimer.d \
./kern/compile/DUMBVM/.depend.runprogram.d \
./kern/compile/DUMBVM/.depend.rwtest.d \
./kern/compile/DUMBVM/.depend.secure.d \
./kern/compile/DUMBVM/.depend.semfs_fsops.d \
./kern/compile/DUMBVM/.depend.semfs_obj.d \
./kern/compile/DUMBVM/.depend.semfs_vnops.d \
./kern/compile/DUMBVM/.depend.semunit.d \
./kern/compile/DUMBVM/.depend.sfs_balloc.d \
./kern/compile/DUMBVM/.depend.sfs_bmap.d \
./kern/compile/DUMBVM/.depend.sfs_dir.d \
./kern/compile/DUMBVM/.depend.sfs_fsops.d \
./kern/compile/DUMBVM/.depend.sfs_inode.d \
./kern/compile/DUMBVM/.depend.sfs_io.d \
./kern/compile/DUMBVM/.depend.sfs_vnops.d \
./kern/compile/DUMBVM/.depend.sha256.d \
./kern/compile/DUMBVM/.depend.snprintf.d \
./kern/compile/DUMBVM/.depend.spinlock.d \
./kern/compile/DUMBVM/.depend.spl.d \
./kern/compile/DUMBVM/.depend.strcat.d \
./kern/compile/DUMBVM/.depend.strchr.d \
./kern/compile/DUMBVM/.depend.strcmp.d \
./kern/compile/DUMBVM/.depend.strcpy.d \
./kern/compile/DUMBVM/.depend.strlen.d \
./kern/compile/DUMBVM/.depend.strrchr.d \
./kern/compile/DUMBVM/.depend.strtok_r.d \
./kern/compile/DUMBVM/.depend.subdi3.d \
./kern/compile/DUMBVM/.depend.switchframe.d \
./kern/compile/DUMBVM/.depend.synch.d \
./kern/compile/DUMBVM/.depend.synchtest.d \
./kern/compile/DUMBVM/.depend.syscall.d \
./kern/compile/DUMBVM/.depend.test161.d \
./kern/compile/DUMBVM/.depend.thread.d \
./kern/compile/DUMBVM/.depend.thread_machdep.d \
./kern/compile/DUMBVM/.depend.threadlist.d \
./kern/compile/DUMBVM/.depend.threadlisttest.d \
./kern/compile/DUMBVM/.depend.threadtest.d \
./kern/compile/DUMBVM/.depend.time.d \
./kern/compile/DUMBVM/.depend.time_syscalls.d \
./kern/compile/DUMBVM/.depend.trap.d \
./kern/compile/DUMBVM/.depend.tt3.d \
./kern/compile/DUMBVM/.depend.ucmpdi2.d \
./kern/compile/DUMBVM/.depend.udivdi3.d \
./kern/compile/DUMBVM/.depend.uio.d \
./kern/compile/DUMBVM/.depend.umoddi3.d \
./kern/compile/DUMBVM/.depend.vfscwd.d \
./kern/compile/DUMBVM/.depend.vfsfail.d \
./kern/compile/DUMBVM/.depend.vfslist.d \
./kern/compile/DUMBVM/.depend.vfslookup.d \
./kern/compile/DUMBVM/.depend.vfspath.d \
./kern/compile/DUMBVM/.depend.vnode.d \
./kern/compile/DUMBVM/.depend.xordi3.d \
./kern/compile/DUMBVM/autoconf.d \
./kern/compile/DUMBVM/vers.d 


# Each subdirectory must supply rules for building sources it contributes
kern/compile/DUMBVM/%.o: ../kern/compile/DUMBVM/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

kern/compile/DUMBVM/%.o: ../kern/compile/DUMBVM/%.S
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


