################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../kern/compile/ASST2/.depend.__printf.c \
../kern/compile/ASST2/.depend.adddi3.c \
../kern/compile/ASST2/.depend.anddi3.c \
../kern/compile/ASST2/.depend.array.c \
../kern/compile/ASST2/.depend.arraytest.c \
../kern/compile/ASST2/.depend.ashldi3.c \
../kern/compile/ASST2/.depend.ashrdi3.c \
../kern/compile/ASST2/.depend.atoi.c \
../kern/compile/ASST2/.depend.autoconf.c \
../kern/compile/ASST2/.depend.beep.c \
../kern/compile/ASST2/.depend.beep_ltimer.c \
../kern/compile/ASST2/.depend.bitmap.c \
../kern/compile/ASST2/.depend.bitmaptest.c \
../kern/compile/ASST2/.depend.bswap.c \
../kern/compile/ASST2/.depend.bzero.c \
../kern/compile/ASST2/.depend.clock.c \
../kern/compile/ASST2/.depend.cmpdi2.c \
../kern/compile/ASST2/.depend.con_lser.c \
../kern/compile/ASST2/.depend.console.c \
../kern/compile/ASST2/.depend.copyinout.c \
../kern/compile/ASST2/.depend.cpu.c \
../kern/compile/ASST2/.depend.device.c \
../kern/compile/ASST2/.depend.devnull.c \
../kern/compile/ASST2/.depend.divdi3.c \
../kern/compile/ASST2/.depend.dumbvm.c \
../kern/compile/ASST2/.depend.emu.c \
../kern/compile/ASST2/.depend.emu_att.c \
../kern/compile/ASST2/.depend.file_syscalls.c \
../kern/compile/ASST2/.depend.fstest.c \
../kern/compile/ASST2/.depend.hmacunit.c \
../kern/compile/ASST2/.depend.iordi3.c \
../kern/compile/ASST2/.depend.kgets.c \
../kern/compile/ASST2/.depend.kmalloc.c \
../kern/compile/ASST2/.depend.kmalloctest.c \
../kern/compile/ASST2/.depend.kprintf.c \
../kern/compile/ASST2/.depend.lamebus.c \
../kern/compile/ASST2/.depend.lamebus_machdep.c \
../kern/compile/ASST2/.depend.lhd.c \
../kern/compile/ASST2/.depend.lhd_att.c \
../kern/compile/ASST2/.depend.lib.c \
../kern/compile/ASST2/.depend.loadelf.c \
../kern/compile/ASST2/.depend.lrandom.c \
../kern/compile/ASST2/.depend.lrandom_att.c \
../kern/compile/ASST2/.depend.lser.c \
../kern/compile/ASST2/.depend.lser_att.c \
../kern/compile/ASST2/.depend.lshldi3.c \
../kern/compile/ASST2/.depend.lshrdi3.c \
../kern/compile/ASST2/.depend.ltimer.c \
../kern/compile/ASST2/.depend.ltimer_att.c \
../kern/compile/ASST2/.depend.ltrace.c \
../kern/compile/ASST2/.depend.ltrace_att.c \
../kern/compile/ASST2/.depend.main.c \
../kern/compile/ASST2/.depend.memcpy.c \
../kern/compile/ASST2/.depend.memmove.c \
../kern/compile/ASST2/.depend.memset.c \
../kern/compile/ASST2/.depend.menu.c \
../kern/compile/ASST2/.depend.misc.c \
../kern/compile/ASST2/.depend.moddi3.c \
../kern/compile/ASST2/.depend.muldi3.c \
../kern/compile/ASST2/.depend.negdi2.c \
../kern/compile/ASST2/.depend.notdi2.c \
../kern/compile/ASST2/.depend.proc.c \
../kern/compile/ASST2/.depend.proc_syscalls.c \
../kern/compile/ASST2/.depend.qdivrem.c \
../kern/compile/ASST2/.depend.ram.c \
../kern/compile/ASST2/.depend.random.c \
../kern/compile/ASST2/.depend.random_lrandom.c \
../kern/compile/ASST2/.depend.rtclock.c \
../kern/compile/ASST2/.depend.rtclock_ltimer.c \
../kern/compile/ASST2/.depend.runprogram.c \
../kern/compile/ASST2/.depend.rwtest.c \
../kern/compile/ASST2/.depend.secure.c \
../kern/compile/ASST2/.depend.semfs_fsops.c \
../kern/compile/ASST2/.depend.semfs_obj.c \
../kern/compile/ASST2/.depend.semfs_vnops.c \
../kern/compile/ASST2/.depend.semunit.c \
../kern/compile/ASST2/.depend.sfs_balloc.c \
../kern/compile/ASST2/.depend.sfs_bmap.c \
../kern/compile/ASST2/.depend.sfs_dir.c \
../kern/compile/ASST2/.depend.sfs_fsops.c \
../kern/compile/ASST2/.depend.sfs_inode.c \
../kern/compile/ASST2/.depend.sfs_io.c \
../kern/compile/ASST2/.depend.sfs_vnops.c \
../kern/compile/ASST2/.depend.sha256.c \
../kern/compile/ASST2/.depend.snprintf.c \
../kern/compile/ASST2/.depend.spinlock.c \
../kern/compile/ASST2/.depend.spl.c \
../kern/compile/ASST2/.depend.strcat.c \
../kern/compile/ASST2/.depend.strchr.c \
../kern/compile/ASST2/.depend.strcmp.c \
../kern/compile/ASST2/.depend.strcpy.c \
../kern/compile/ASST2/.depend.strlen.c \
../kern/compile/ASST2/.depend.strrchr.c \
../kern/compile/ASST2/.depend.strtok_r.c \
../kern/compile/ASST2/.depend.subdi3.c \
../kern/compile/ASST2/.depend.switchframe.c \
../kern/compile/ASST2/.depend.synch.c \
../kern/compile/ASST2/.depend.synchtest.c \
../kern/compile/ASST2/.depend.syscall.c \
../kern/compile/ASST2/.depend.test161.c \
../kern/compile/ASST2/.depend.thread.c \
../kern/compile/ASST2/.depend.thread_machdep.c \
../kern/compile/ASST2/.depend.threadlist.c \
../kern/compile/ASST2/.depend.threadlisttest.c \
../kern/compile/ASST2/.depend.threadtest.c \
../kern/compile/ASST2/.depend.time.c \
../kern/compile/ASST2/.depend.time_syscalls.c \
../kern/compile/ASST2/.depend.trap.c \
../kern/compile/ASST2/.depend.tt3.c \
../kern/compile/ASST2/.depend.ucmpdi2.c \
../kern/compile/ASST2/.depend.udivdi3.c \
../kern/compile/ASST2/.depend.uio.c \
../kern/compile/ASST2/.depend.umoddi3.c \
../kern/compile/ASST2/.depend.vfscwd.c \
../kern/compile/ASST2/.depend.vfsfail.c \
../kern/compile/ASST2/.depend.vfslist.c \
../kern/compile/ASST2/.depend.vfslookup.c \
../kern/compile/ASST2/.depend.vfspath.c \
../kern/compile/ASST2/.depend.vnode.c \
../kern/compile/ASST2/.depend.xordi3.c \
../kern/compile/ASST2/autoconf.c \
../kern/compile/ASST2/vers.c 

O_SRCS += \
../kern/compile/ASST2/__printf.o \
../kern/compile/ASST2/adddi3.o \
../kern/compile/ASST2/anddi3.o \
../kern/compile/ASST2/array.o \
../kern/compile/ASST2/arraytest.o \
../kern/compile/ASST2/ashldi3.o \
../kern/compile/ASST2/ashrdi3.o \
../kern/compile/ASST2/atoi.o \
../kern/compile/ASST2/autoconf.o \
../kern/compile/ASST2/beep.o \
../kern/compile/ASST2/beep_ltimer.o \
../kern/compile/ASST2/bitmap.o \
../kern/compile/ASST2/bitmaptest.o \
../kern/compile/ASST2/bswap.o \
../kern/compile/ASST2/bzero.o \
../kern/compile/ASST2/cache-mips161.o \
../kern/compile/ASST2/clock.o \
../kern/compile/ASST2/cmpdi2.o \
../kern/compile/ASST2/con_lser.o \
../kern/compile/ASST2/console.o \
../kern/compile/ASST2/copyinout.o \
../kern/compile/ASST2/cpu.o \
../kern/compile/ASST2/device.o \
../kern/compile/ASST2/devnull.o \
../kern/compile/ASST2/divdi3.o \
../kern/compile/ASST2/dumbvm.o \
../kern/compile/ASST2/emu.o \
../kern/compile/ASST2/emu_att.o \
../kern/compile/ASST2/exception-mips1.o \
../kern/compile/ASST2/file_syscalls.o \
../kern/compile/ASST2/fstest.o \
../kern/compile/ASST2/hmacunit.o \
../kern/compile/ASST2/iordi3.o \
../kern/compile/ASST2/kgets.o \
../kern/compile/ASST2/kmalloc.o \
../kern/compile/ASST2/kmalloctest.o \
../kern/compile/ASST2/kprintf.o \
../kern/compile/ASST2/lamebus.o \
../kern/compile/ASST2/lamebus_machdep.o \
../kern/compile/ASST2/lhd.o \
../kern/compile/ASST2/lhd_att.o \
../kern/compile/ASST2/lib.o \
../kern/compile/ASST2/loadelf.o \
../kern/compile/ASST2/lrandom.o \
../kern/compile/ASST2/lrandom_att.o \
../kern/compile/ASST2/lser.o \
../kern/compile/ASST2/lser_att.o \
../kern/compile/ASST2/lshldi3.o \
../kern/compile/ASST2/lshrdi3.o \
../kern/compile/ASST2/ltimer.o \
../kern/compile/ASST2/ltimer_att.o \
../kern/compile/ASST2/ltrace.o \
../kern/compile/ASST2/ltrace_att.o \
../kern/compile/ASST2/main.o \
../kern/compile/ASST2/memcpy.o \
../kern/compile/ASST2/memmove.o \
../kern/compile/ASST2/memset.o \
../kern/compile/ASST2/menu.o \
../kern/compile/ASST2/misc.o \
../kern/compile/ASST2/moddi3.o \
../kern/compile/ASST2/muldi3.o \
../kern/compile/ASST2/negdi2.o \
../kern/compile/ASST2/notdi2.o \
../kern/compile/ASST2/proc.o \
../kern/compile/ASST2/proc_syscalls.o \
../kern/compile/ASST2/qdivrem.o \
../kern/compile/ASST2/ram.o \
../kern/compile/ASST2/random.o \
../kern/compile/ASST2/random_lrandom.o \
../kern/compile/ASST2/rtclock.o \
../kern/compile/ASST2/rtclock_ltimer.o \
../kern/compile/ASST2/runprogram.o \
../kern/compile/ASST2/rwtest.o \
../kern/compile/ASST2/secure.o \
../kern/compile/ASST2/semfs_fsops.o \
../kern/compile/ASST2/semfs_obj.o \
../kern/compile/ASST2/semfs_vnops.o \
../kern/compile/ASST2/semunit.o \
../kern/compile/ASST2/setjmp.o \
../kern/compile/ASST2/sfs_balloc.o \
../kern/compile/ASST2/sfs_bmap.o \
../kern/compile/ASST2/sfs_dir.o \
../kern/compile/ASST2/sfs_fsops.o \
../kern/compile/ASST2/sfs_inode.o \
../kern/compile/ASST2/sfs_io.o \
../kern/compile/ASST2/sfs_vnops.o \
../kern/compile/ASST2/sha256.o \
../kern/compile/ASST2/snprintf.o \
../kern/compile/ASST2/spinlock.o \
../kern/compile/ASST2/spl.o \
../kern/compile/ASST2/start.o \
../kern/compile/ASST2/strcat.o \
../kern/compile/ASST2/strchr.o \
../kern/compile/ASST2/strcmp.o \
../kern/compile/ASST2/strcpy.o \
../kern/compile/ASST2/strlen.o \
../kern/compile/ASST2/strrchr.o \
../kern/compile/ASST2/strtok_r.o \
../kern/compile/ASST2/subdi3.o \
../kern/compile/ASST2/switch.o \
../kern/compile/ASST2/switchframe.o \
../kern/compile/ASST2/synch.o \
../kern/compile/ASST2/synchtest.o \
../kern/compile/ASST2/syscall.o \
../kern/compile/ASST2/test161.o \
../kern/compile/ASST2/thread.o \
../kern/compile/ASST2/thread_machdep.o \
../kern/compile/ASST2/threadlist.o \
../kern/compile/ASST2/threadlisttest.o \
../kern/compile/ASST2/threadstart.o \
../kern/compile/ASST2/threadtest.o \
../kern/compile/ASST2/time.o \
../kern/compile/ASST2/time_syscalls.o \
../kern/compile/ASST2/tlb-mips161.o \
../kern/compile/ASST2/trap.o \
../kern/compile/ASST2/tt3.o \
../kern/compile/ASST2/ucmpdi2.o \
../kern/compile/ASST2/udivdi3.o \
../kern/compile/ASST2/uio.o \
../kern/compile/ASST2/umoddi3.o \
../kern/compile/ASST2/vers.o \
../kern/compile/ASST2/vfscwd.o \
../kern/compile/ASST2/vfsfail.o \
../kern/compile/ASST2/vfslist.o \
../kern/compile/ASST2/vfslookup.o \
../kern/compile/ASST2/vfspath.o \
../kern/compile/ASST2/vnode.o \
../kern/compile/ASST2/xordi3.o 

S_UPPER_SRCS += \
../kern/compile/ASST2/.depend.cache-mips161.S \
../kern/compile/ASST2/.depend.exception-mips1.S \
../kern/compile/ASST2/.depend.setjmp.S \
../kern/compile/ASST2/.depend.start.S \
../kern/compile/ASST2/.depend.switch.S \
../kern/compile/ASST2/.depend.threadstart.S \
../kern/compile/ASST2/.depend.tlb-mips161.S 

OBJS += \
./kern/compile/ASST2/.depend.__printf.o \
./kern/compile/ASST2/.depend.adddi3.o \
./kern/compile/ASST2/.depend.anddi3.o \
./kern/compile/ASST2/.depend.array.o \
./kern/compile/ASST2/.depend.arraytest.o \
./kern/compile/ASST2/.depend.ashldi3.o \
./kern/compile/ASST2/.depend.ashrdi3.o \
./kern/compile/ASST2/.depend.atoi.o \
./kern/compile/ASST2/.depend.autoconf.o \
./kern/compile/ASST2/.depend.beep.o \
./kern/compile/ASST2/.depend.beep_ltimer.o \
./kern/compile/ASST2/.depend.bitmap.o \
./kern/compile/ASST2/.depend.bitmaptest.o \
./kern/compile/ASST2/.depend.bswap.o \
./kern/compile/ASST2/.depend.bzero.o \
./kern/compile/ASST2/.depend.cache-mips161.o \
./kern/compile/ASST2/.depend.clock.o \
./kern/compile/ASST2/.depend.cmpdi2.o \
./kern/compile/ASST2/.depend.con_lser.o \
./kern/compile/ASST2/.depend.console.o \
./kern/compile/ASST2/.depend.copyinout.o \
./kern/compile/ASST2/.depend.cpu.o \
./kern/compile/ASST2/.depend.device.o \
./kern/compile/ASST2/.depend.devnull.o \
./kern/compile/ASST2/.depend.divdi3.o \
./kern/compile/ASST2/.depend.dumbvm.o \
./kern/compile/ASST2/.depend.emu.o \
./kern/compile/ASST2/.depend.emu_att.o \
./kern/compile/ASST2/.depend.exception-mips1.o \
./kern/compile/ASST2/.depend.file_syscalls.o \
./kern/compile/ASST2/.depend.fstest.o \
./kern/compile/ASST2/.depend.hmacunit.o \
./kern/compile/ASST2/.depend.iordi3.o \
./kern/compile/ASST2/.depend.kgets.o \
./kern/compile/ASST2/.depend.kmalloc.o \
./kern/compile/ASST2/.depend.kmalloctest.o \
./kern/compile/ASST2/.depend.kprintf.o \
./kern/compile/ASST2/.depend.lamebus.o \
./kern/compile/ASST2/.depend.lamebus_machdep.o \
./kern/compile/ASST2/.depend.lhd.o \
./kern/compile/ASST2/.depend.lhd_att.o \
./kern/compile/ASST2/.depend.lib.o \
./kern/compile/ASST2/.depend.loadelf.o \
./kern/compile/ASST2/.depend.lrandom.o \
./kern/compile/ASST2/.depend.lrandom_att.o \
./kern/compile/ASST2/.depend.lser.o \
./kern/compile/ASST2/.depend.lser_att.o \
./kern/compile/ASST2/.depend.lshldi3.o \
./kern/compile/ASST2/.depend.lshrdi3.o \
./kern/compile/ASST2/.depend.ltimer.o \
./kern/compile/ASST2/.depend.ltimer_att.o \
./kern/compile/ASST2/.depend.ltrace.o \
./kern/compile/ASST2/.depend.ltrace_att.o \
./kern/compile/ASST2/.depend.main.o \
./kern/compile/ASST2/.depend.memcpy.o \
./kern/compile/ASST2/.depend.memmove.o \
./kern/compile/ASST2/.depend.memset.o \
./kern/compile/ASST2/.depend.menu.o \
./kern/compile/ASST2/.depend.misc.o \
./kern/compile/ASST2/.depend.moddi3.o \
./kern/compile/ASST2/.depend.muldi3.o \
./kern/compile/ASST2/.depend.negdi2.o \
./kern/compile/ASST2/.depend.notdi2.o \
./kern/compile/ASST2/.depend.proc.o \
./kern/compile/ASST2/.depend.proc_syscalls.o \
./kern/compile/ASST2/.depend.qdivrem.o \
./kern/compile/ASST2/.depend.ram.o \
./kern/compile/ASST2/.depend.random.o \
./kern/compile/ASST2/.depend.random_lrandom.o \
./kern/compile/ASST2/.depend.rtclock.o \
./kern/compile/ASST2/.depend.rtclock_ltimer.o \
./kern/compile/ASST2/.depend.runprogram.o \
./kern/compile/ASST2/.depend.rwtest.o \
./kern/compile/ASST2/.depend.secure.o \
./kern/compile/ASST2/.depend.semfs_fsops.o \
./kern/compile/ASST2/.depend.semfs_obj.o \
./kern/compile/ASST2/.depend.semfs_vnops.o \
./kern/compile/ASST2/.depend.semunit.o \
./kern/compile/ASST2/.depend.setjmp.o \
./kern/compile/ASST2/.depend.sfs_balloc.o \
./kern/compile/ASST2/.depend.sfs_bmap.o \
./kern/compile/ASST2/.depend.sfs_dir.o \
./kern/compile/ASST2/.depend.sfs_fsops.o \
./kern/compile/ASST2/.depend.sfs_inode.o \
./kern/compile/ASST2/.depend.sfs_io.o \
./kern/compile/ASST2/.depend.sfs_vnops.o \
./kern/compile/ASST2/.depend.sha256.o \
./kern/compile/ASST2/.depend.snprintf.o \
./kern/compile/ASST2/.depend.spinlock.o \
./kern/compile/ASST2/.depend.spl.o \
./kern/compile/ASST2/.depend.start.o \
./kern/compile/ASST2/.depend.strcat.o \
./kern/compile/ASST2/.depend.strchr.o \
./kern/compile/ASST2/.depend.strcmp.o \
./kern/compile/ASST2/.depend.strcpy.o \
./kern/compile/ASST2/.depend.strlen.o \
./kern/compile/ASST2/.depend.strrchr.o \
./kern/compile/ASST2/.depend.strtok_r.o \
./kern/compile/ASST2/.depend.subdi3.o \
./kern/compile/ASST2/.depend.switch.o \
./kern/compile/ASST2/.depend.switchframe.o \
./kern/compile/ASST2/.depend.synch.o \
./kern/compile/ASST2/.depend.synchtest.o \
./kern/compile/ASST2/.depend.syscall.o \
./kern/compile/ASST2/.depend.test161.o \
./kern/compile/ASST2/.depend.thread.o \
./kern/compile/ASST2/.depend.thread_machdep.o \
./kern/compile/ASST2/.depend.threadlist.o \
./kern/compile/ASST2/.depend.threadlisttest.o \
./kern/compile/ASST2/.depend.threadstart.o \
./kern/compile/ASST2/.depend.threadtest.o \
./kern/compile/ASST2/.depend.time.o \
./kern/compile/ASST2/.depend.time_syscalls.o \
./kern/compile/ASST2/.depend.tlb-mips161.o \
./kern/compile/ASST2/.depend.trap.o \
./kern/compile/ASST2/.depend.tt3.o \
./kern/compile/ASST2/.depend.ucmpdi2.o \
./kern/compile/ASST2/.depend.udivdi3.o \
./kern/compile/ASST2/.depend.uio.o \
./kern/compile/ASST2/.depend.umoddi3.o \
./kern/compile/ASST2/.depend.vfscwd.o \
./kern/compile/ASST2/.depend.vfsfail.o \
./kern/compile/ASST2/.depend.vfslist.o \
./kern/compile/ASST2/.depend.vfslookup.o \
./kern/compile/ASST2/.depend.vfspath.o \
./kern/compile/ASST2/.depend.vnode.o \
./kern/compile/ASST2/.depend.xordi3.o \
./kern/compile/ASST2/autoconf.o \
./kern/compile/ASST2/vers.o 

C_DEPS += \
./kern/compile/ASST2/.depend.__printf.d \
./kern/compile/ASST2/.depend.adddi3.d \
./kern/compile/ASST2/.depend.anddi3.d \
./kern/compile/ASST2/.depend.array.d \
./kern/compile/ASST2/.depend.arraytest.d \
./kern/compile/ASST2/.depend.ashldi3.d \
./kern/compile/ASST2/.depend.ashrdi3.d \
./kern/compile/ASST2/.depend.atoi.d \
./kern/compile/ASST2/.depend.autoconf.d \
./kern/compile/ASST2/.depend.beep.d \
./kern/compile/ASST2/.depend.beep_ltimer.d \
./kern/compile/ASST2/.depend.bitmap.d \
./kern/compile/ASST2/.depend.bitmaptest.d \
./kern/compile/ASST2/.depend.bswap.d \
./kern/compile/ASST2/.depend.bzero.d \
./kern/compile/ASST2/.depend.clock.d \
./kern/compile/ASST2/.depend.cmpdi2.d \
./kern/compile/ASST2/.depend.con_lser.d \
./kern/compile/ASST2/.depend.console.d \
./kern/compile/ASST2/.depend.copyinout.d \
./kern/compile/ASST2/.depend.cpu.d \
./kern/compile/ASST2/.depend.device.d \
./kern/compile/ASST2/.depend.devnull.d \
./kern/compile/ASST2/.depend.divdi3.d \
./kern/compile/ASST2/.depend.dumbvm.d \
./kern/compile/ASST2/.depend.emu.d \
./kern/compile/ASST2/.depend.emu_att.d \
./kern/compile/ASST2/.depend.file_syscalls.d \
./kern/compile/ASST2/.depend.fstest.d \
./kern/compile/ASST2/.depend.hmacunit.d \
./kern/compile/ASST2/.depend.iordi3.d \
./kern/compile/ASST2/.depend.kgets.d \
./kern/compile/ASST2/.depend.kmalloc.d \
./kern/compile/ASST2/.depend.kmalloctest.d \
./kern/compile/ASST2/.depend.kprintf.d \
./kern/compile/ASST2/.depend.lamebus.d \
./kern/compile/ASST2/.depend.lamebus_machdep.d \
./kern/compile/ASST2/.depend.lhd.d \
./kern/compile/ASST2/.depend.lhd_att.d \
./kern/compile/ASST2/.depend.lib.d \
./kern/compile/ASST2/.depend.loadelf.d \
./kern/compile/ASST2/.depend.lrandom.d \
./kern/compile/ASST2/.depend.lrandom_att.d \
./kern/compile/ASST2/.depend.lser.d \
./kern/compile/ASST2/.depend.lser_att.d \
./kern/compile/ASST2/.depend.lshldi3.d \
./kern/compile/ASST2/.depend.lshrdi3.d \
./kern/compile/ASST2/.depend.ltimer.d \
./kern/compile/ASST2/.depend.ltimer_att.d \
./kern/compile/ASST2/.depend.ltrace.d \
./kern/compile/ASST2/.depend.ltrace_att.d \
./kern/compile/ASST2/.depend.main.d \
./kern/compile/ASST2/.depend.memcpy.d \
./kern/compile/ASST2/.depend.memmove.d \
./kern/compile/ASST2/.depend.memset.d \
./kern/compile/ASST2/.depend.menu.d \
./kern/compile/ASST2/.depend.misc.d \
./kern/compile/ASST2/.depend.moddi3.d \
./kern/compile/ASST2/.depend.muldi3.d \
./kern/compile/ASST2/.depend.negdi2.d \
./kern/compile/ASST2/.depend.notdi2.d \
./kern/compile/ASST2/.depend.proc.d \
./kern/compile/ASST2/.depend.proc_syscalls.d \
./kern/compile/ASST2/.depend.qdivrem.d \
./kern/compile/ASST2/.depend.ram.d \
./kern/compile/ASST2/.depend.random.d \
./kern/compile/ASST2/.depend.random_lrandom.d \
./kern/compile/ASST2/.depend.rtclock.d \
./kern/compile/ASST2/.depend.rtclock_ltimer.d \
./kern/compile/ASST2/.depend.runprogram.d \
./kern/compile/ASST2/.depend.rwtest.d \
./kern/compile/ASST2/.depend.secure.d \
./kern/compile/ASST2/.depend.semfs_fsops.d \
./kern/compile/ASST2/.depend.semfs_obj.d \
./kern/compile/ASST2/.depend.semfs_vnops.d \
./kern/compile/ASST2/.depend.semunit.d \
./kern/compile/ASST2/.depend.sfs_balloc.d \
./kern/compile/ASST2/.depend.sfs_bmap.d \
./kern/compile/ASST2/.depend.sfs_dir.d \
./kern/compile/ASST2/.depend.sfs_fsops.d \
./kern/compile/ASST2/.depend.sfs_inode.d \
./kern/compile/ASST2/.depend.sfs_io.d \
./kern/compile/ASST2/.depend.sfs_vnops.d \
./kern/compile/ASST2/.depend.sha256.d \
./kern/compile/ASST2/.depend.snprintf.d \
./kern/compile/ASST2/.depend.spinlock.d \
./kern/compile/ASST2/.depend.spl.d \
./kern/compile/ASST2/.depend.strcat.d \
./kern/compile/ASST2/.depend.strchr.d \
./kern/compile/ASST2/.depend.strcmp.d \
./kern/compile/ASST2/.depend.strcpy.d \
./kern/compile/ASST2/.depend.strlen.d \
./kern/compile/ASST2/.depend.strrchr.d \
./kern/compile/ASST2/.depend.strtok_r.d \
./kern/compile/ASST2/.depend.subdi3.d \
./kern/compile/ASST2/.depend.switchframe.d \
./kern/compile/ASST2/.depend.synch.d \
./kern/compile/ASST2/.depend.synchtest.d \
./kern/compile/ASST2/.depend.syscall.d \
./kern/compile/ASST2/.depend.test161.d \
./kern/compile/ASST2/.depend.thread.d \
./kern/compile/ASST2/.depend.thread_machdep.d \
./kern/compile/ASST2/.depend.threadlist.d \
./kern/compile/ASST2/.depend.threadlisttest.d \
./kern/compile/ASST2/.depend.threadtest.d \
./kern/compile/ASST2/.depend.time.d \
./kern/compile/ASST2/.depend.time_syscalls.d \
./kern/compile/ASST2/.depend.trap.d \
./kern/compile/ASST2/.depend.tt3.d \
./kern/compile/ASST2/.depend.ucmpdi2.d \
./kern/compile/ASST2/.depend.udivdi3.d \
./kern/compile/ASST2/.depend.uio.d \
./kern/compile/ASST2/.depend.umoddi3.d \
./kern/compile/ASST2/.depend.vfscwd.d \
./kern/compile/ASST2/.depend.vfsfail.d \
./kern/compile/ASST2/.depend.vfslist.d \
./kern/compile/ASST2/.depend.vfslookup.d \
./kern/compile/ASST2/.depend.vfspath.d \
./kern/compile/ASST2/.depend.vnode.d \
./kern/compile/ASST2/.depend.xordi3.d \
./kern/compile/ASST2/autoconf.d \
./kern/compile/ASST2/vers.d 


# Each subdirectory must supply rules for building sources it contributes
kern/compile/ASST2/%.o: ../kern/compile/ASST2/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

kern/compile/ASST2/%.o: ../kern/compile/ASST2/%.S
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


