################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../kern/compile/ASST3/.depend.__printf.c \
../kern/compile/ASST3/.depend.adddi3.c \
../kern/compile/ASST3/.depend.addrspace.c \
../kern/compile/ASST3/.depend.anddi3.c \
../kern/compile/ASST3/.depend.array.c \
../kern/compile/ASST3/.depend.arraytest.c \
../kern/compile/ASST3/.depend.ashldi3.c \
../kern/compile/ASST3/.depend.ashrdi3.c \
../kern/compile/ASST3/.depend.atoi.c \
../kern/compile/ASST3/.depend.autoconf.c \
../kern/compile/ASST3/.depend.beep.c \
../kern/compile/ASST3/.depend.beep_ltimer.c \
../kern/compile/ASST3/.depend.bitmap.c \
../kern/compile/ASST3/.depend.bitmaptest.c \
../kern/compile/ASST3/.depend.bswap.c \
../kern/compile/ASST3/.depend.bzero.c \
../kern/compile/ASST3/.depend.clock.c \
../kern/compile/ASST3/.depend.cmpdi2.c \
../kern/compile/ASST3/.depend.con_lser.c \
../kern/compile/ASST3/.depend.console.c \
../kern/compile/ASST3/.depend.copyinout.c \
../kern/compile/ASST3/.depend.cpu.c \
../kern/compile/ASST3/.depend.device.c \
../kern/compile/ASST3/.depend.devnull.c \
../kern/compile/ASST3/.depend.divdi3.c \
../kern/compile/ASST3/.depend.emu.c \
../kern/compile/ASST3/.depend.emu_att.c \
../kern/compile/ASST3/.depend.file_syscalls.c \
../kern/compile/ASST3/.depend.fstest.c \
../kern/compile/ASST3/.depend.hmacunit.c \
../kern/compile/ASST3/.depend.iordi3.c \
../kern/compile/ASST3/.depend.kgets.c \
../kern/compile/ASST3/.depend.kmalloc.c \
../kern/compile/ASST3/.depend.kmalloctest.c \
../kern/compile/ASST3/.depend.kprintf.c \
../kern/compile/ASST3/.depend.lamebus.c \
../kern/compile/ASST3/.depend.lamebus_machdep.c \
../kern/compile/ASST3/.depend.lhd.c \
../kern/compile/ASST3/.depend.lhd_att.c \
../kern/compile/ASST3/.depend.lib.c \
../kern/compile/ASST3/.depend.loadelf.c \
../kern/compile/ASST3/.depend.lrandom.c \
../kern/compile/ASST3/.depend.lrandom_att.c \
../kern/compile/ASST3/.depend.lser.c \
../kern/compile/ASST3/.depend.lser_att.c \
../kern/compile/ASST3/.depend.lshldi3.c \
../kern/compile/ASST3/.depend.lshrdi3.c \
../kern/compile/ASST3/.depend.ltimer.c \
../kern/compile/ASST3/.depend.ltimer_att.c \
../kern/compile/ASST3/.depend.ltrace.c \
../kern/compile/ASST3/.depend.ltrace_att.c \
../kern/compile/ASST3/.depend.main.c \
../kern/compile/ASST3/.depend.memcpy.c \
../kern/compile/ASST3/.depend.memmove.c \
../kern/compile/ASST3/.depend.memset.c \
../kern/compile/ASST3/.depend.menu.c \
../kern/compile/ASST3/.depend.misc.c \
../kern/compile/ASST3/.depend.moddi3.c \
../kern/compile/ASST3/.depend.muldi3.c \
../kern/compile/ASST3/.depend.myvm.c \
../kern/compile/ASST3/.depend.negdi2.c \
../kern/compile/ASST3/.depend.notdi2.c \
../kern/compile/ASST3/.depend.proc.c \
../kern/compile/ASST3/.depend.proc_syscalls.c \
../kern/compile/ASST3/.depend.qdivrem.c \
../kern/compile/ASST3/.depend.ram.c \
../kern/compile/ASST3/.depend.random.c \
../kern/compile/ASST3/.depend.random_lrandom.c \
../kern/compile/ASST3/.depend.rtclock.c \
../kern/compile/ASST3/.depend.rtclock_ltimer.c \
../kern/compile/ASST3/.depend.runprogram.c \
../kern/compile/ASST3/.depend.rwtest.c \
../kern/compile/ASST3/.depend.secure.c \
../kern/compile/ASST3/.depend.semfs_fsops.c \
../kern/compile/ASST3/.depend.semfs_obj.c \
../kern/compile/ASST3/.depend.semfs_vnops.c \
../kern/compile/ASST3/.depend.semunit.c \
../kern/compile/ASST3/.depend.sfs_balloc.c \
../kern/compile/ASST3/.depend.sfs_bmap.c \
../kern/compile/ASST3/.depend.sfs_dir.c \
../kern/compile/ASST3/.depend.sfs_fsops.c \
../kern/compile/ASST3/.depend.sfs_inode.c \
../kern/compile/ASST3/.depend.sfs_io.c \
../kern/compile/ASST3/.depend.sfs_vnops.c \
../kern/compile/ASST3/.depend.sha256.c \
../kern/compile/ASST3/.depend.snprintf.c \
../kern/compile/ASST3/.depend.spinlock.c \
../kern/compile/ASST3/.depend.spl.c \
../kern/compile/ASST3/.depend.strcat.c \
../kern/compile/ASST3/.depend.strchr.c \
../kern/compile/ASST3/.depend.strcmp.c \
../kern/compile/ASST3/.depend.strcpy.c \
../kern/compile/ASST3/.depend.strlen.c \
../kern/compile/ASST3/.depend.strrchr.c \
../kern/compile/ASST3/.depend.strtok_r.c \
../kern/compile/ASST3/.depend.subdi3.c \
../kern/compile/ASST3/.depend.switchframe.c \
../kern/compile/ASST3/.depend.synch.c \
../kern/compile/ASST3/.depend.synchtest.c \
../kern/compile/ASST3/.depend.syscall.c \
../kern/compile/ASST3/.depend.test161.c \
../kern/compile/ASST3/.depend.thread.c \
../kern/compile/ASST3/.depend.thread_machdep.c \
../kern/compile/ASST3/.depend.threadlist.c \
../kern/compile/ASST3/.depend.threadlisttest.c \
../kern/compile/ASST3/.depend.threadtest.c \
../kern/compile/ASST3/.depend.time.c \
../kern/compile/ASST3/.depend.time_syscalls.c \
../kern/compile/ASST3/.depend.trap.c \
../kern/compile/ASST3/.depend.tt3.c \
../kern/compile/ASST3/.depend.ucmpdi2.c \
../kern/compile/ASST3/.depend.udivdi3.c \
../kern/compile/ASST3/.depend.uio.c \
../kern/compile/ASST3/.depend.umoddi3.c \
../kern/compile/ASST3/.depend.vfscwd.c \
../kern/compile/ASST3/.depend.vfsfail.c \
../kern/compile/ASST3/.depend.vfslist.c \
../kern/compile/ASST3/.depend.vfslookup.c \
../kern/compile/ASST3/.depend.vfspath.c \
../kern/compile/ASST3/.depend.vnode.c \
../kern/compile/ASST3/.depend.xordi3.c \
../kern/compile/ASST3/autoconf.c \
../kern/compile/ASST3/vers.c 

O_SRCS += \
../kern/compile/ASST3/__printf.o \
../kern/compile/ASST3/adddi3.o \
../kern/compile/ASST3/addrspace.o \
../kern/compile/ASST3/anddi3.o \
../kern/compile/ASST3/array.o \
../kern/compile/ASST3/arraytest.o \
../kern/compile/ASST3/ashldi3.o \
../kern/compile/ASST3/ashrdi3.o \
../kern/compile/ASST3/atoi.o \
../kern/compile/ASST3/autoconf.o \
../kern/compile/ASST3/beep.o \
../kern/compile/ASST3/beep_ltimer.o \
../kern/compile/ASST3/bitmap.o \
../kern/compile/ASST3/bitmaptest.o \
../kern/compile/ASST3/bswap.o \
../kern/compile/ASST3/bzero.o \
../kern/compile/ASST3/cache-mips161.o \
../kern/compile/ASST3/clock.o \
../kern/compile/ASST3/cmpdi2.o \
../kern/compile/ASST3/con_lser.o \
../kern/compile/ASST3/console.o \
../kern/compile/ASST3/copyinout.o \
../kern/compile/ASST3/cpu.o \
../kern/compile/ASST3/device.o \
../kern/compile/ASST3/devnull.o \
../kern/compile/ASST3/divdi3.o \
../kern/compile/ASST3/emu.o \
../kern/compile/ASST3/emu_att.o \
../kern/compile/ASST3/exception-mips1.o \
../kern/compile/ASST3/file_syscalls.o \
../kern/compile/ASST3/fstest.o \
../kern/compile/ASST3/hmacunit.o \
../kern/compile/ASST3/iordi3.o \
../kern/compile/ASST3/kgets.o \
../kern/compile/ASST3/kmalloc.o \
../kern/compile/ASST3/kmalloctest.o \
../kern/compile/ASST3/kprintf.o \
../kern/compile/ASST3/lamebus.o \
../kern/compile/ASST3/lamebus_machdep.o \
../kern/compile/ASST3/lhd.o \
../kern/compile/ASST3/lhd_att.o \
../kern/compile/ASST3/lib.o \
../kern/compile/ASST3/loadelf.o \
../kern/compile/ASST3/lrandom.o \
../kern/compile/ASST3/lrandom_att.o \
../kern/compile/ASST3/lser.o \
../kern/compile/ASST3/lser_att.o \
../kern/compile/ASST3/lshldi3.o \
../kern/compile/ASST3/lshrdi3.o \
../kern/compile/ASST3/ltimer.o \
../kern/compile/ASST3/ltimer_att.o \
../kern/compile/ASST3/ltrace.o \
../kern/compile/ASST3/ltrace_att.o \
../kern/compile/ASST3/main.o \
../kern/compile/ASST3/memcpy.o \
../kern/compile/ASST3/memmove.o \
../kern/compile/ASST3/memset.o \
../kern/compile/ASST3/menu.o \
../kern/compile/ASST3/misc.o \
../kern/compile/ASST3/moddi3.o \
../kern/compile/ASST3/muldi3.o \
../kern/compile/ASST3/myvm.o \
../kern/compile/ASST3/negdi2.o \
../kern/compile/ASST3/notdi2.o \
../kern/compile/ASST3/proc.o \
../kern/compile/ASST3/proc_syscalls.o \
../kern/compile/ASST3/qdivrem.o \
../kern/compile/ASST3/ram.o \
../kern/compile/ASST3/random.o \
../kern/compile/ASST3/random_lrandom.o \
../kern/compile/ASST3/rtclock.o \
../kern/compile/ASST3/rtclock_ltimer.o \
../kern/compile/ASST3/runprogram.o \
../kern/compile/ASST3/rwtest.o \
../kern/compile/ASST3/secure.o \
../kern/compile/ASST3/semfs_fsops.o \
../kern/compile/ASST3/semfs_obj.o \
../kern/compile/ASST3/semfs_vnops.o \
../kern/compile/ASST3/semunit.o \
../kern/compile/ASST3/setjmp.o \
../kern/compile/ASST3/sfs_balloc.o \
../kern/compile/ASST3/sfs_bmap.o \
../kern/compile/ASST3/sfs_dir.o \
../kern/compile/ASST3/sfs_fsops.o \
../kern/compile/ASST3/sfs_inode.o \
../kern/compile/ASST3/sfs_io.o \
../kern/compile/ASST3/sfs_vnops.o \
../kern/compile/ASST3/sha256.o \
../kern/compile/ASST3/snprintf.o \
../kern/compile/ASST3/spinlock.o \
../kern/compile/ASST3/spl.o \
../kern/compile/ASST3/start.o \
../kern/compile/ASST3/strcat.o \
../kern/compile/ASST3/strchr.o \
../kern/compile/ASST3/strcmp.o \
../kern/compile/ASST3/strcpy.o \
../kern/compile/ASST3/strlen.o \
../kern/compile/ASST3/strrchr.o \
../kern/compile/ASST3/strtok_r.o \
../kern/compile/ASST3/subdi3.o \
../kern/compile/ASST3/switch.o \
../kern/compile/ASST3/switchframe.o \
../kern/compile/ASST3/synch.o \
../kern/compile/ASST3/synchtest.o \
../kern/compile/ASST3/syscall.o \
../kern/compile/ASST3/test161.o \
../kern/compile/ASST3/thread.o \
../kern/compile/ASST3/thread_machdep.o \
../kern/compile/ASST3/threadlist.o \
../kern/compile/ASST3/threadlisttest.o \
../kern/compile/ASST3/threadstart.o \
../kern/compile/ASST3/threadtest.o \
../kern/compile/ASST3/time.o \
../kern/compile/ASST3/time_syscalls.o \
../kern/compile/ASST3/tlb-mips161.o \
../kern/compile/ASST3/trap.o \
../kern/compile/ASST3/tt3.o \
../kern/compile/ASST3/ucmpdi2.o \
../kern/compile/ASST3/udivdi3.o \
../kern/compile/ASST3/uio.o \
../kern/compile/ASST3/umoddi3.o \
../kern/compile/ASST3/vers.o \
../kern/compile/ASST3/vfscwd.o \
../kern/compile/ASST3/vfsfail.o \
../kern/compile/ASST3/vfslist.o \
../kern/compile/ASST3/vfslookup.o \
../kern/compile/ASST3/vfspath.o \
../kern/compile/ASST3/vnode.o \
../kern/compile/ASST3/xordi3.o 

S_UPPER_SRCS += \
../kern/compile/ASST3/.depend.cache-mips161.S \
../kern/compile/ASST3/.depend.exception-mips1.S \
../kern/compile/ASST3/.depend.setjmp.S \
../kern/compile/ASST3/.depend.start.S \
../kern/compile/ASST3/.depend.switch.S \
../kern/compile/ASST3/.depend.threadstart.S \
../kern/compile/ASST3/.depend.tlb-mips161.S 

OBJS += \
./kern/compile/ASST3/.depend.__printf.o \
./kern/compile/ASST3/.depend.adddi3.o \
./kern/compile/ASST3/.depend.addrspace.o \
./kern/compile/ASST3/.depend.anddi3.o \
./kern/compile/ASST3/.depend.array.o \
./kern/compile/ASST3/.depend.arraytest.o \
./kern/compile/ASST3/.depend.ashldi3.o \
./kern/compile/ASST3/.depend.ashrdi3.o \
./kern/compile/ASST3/.depend.atoi.o \
./kern/compile/ASST3/.depend.autoconf.o \
./kern/compile/ASST3/.depend.beep.o \
./kern/compile/ASST3/.depend.beep_ltimer.o \
./kern/compile/ASST3/.depend.bitmap.o \
./kern/compile/ASST3/.depend.bitmaptest.o \
./kern/compile/ASST3/.depend.bswap.o \
./kern/compile/ASST3/.depend.bzero.o \
./kern/compile/ASST3/.depend.cache-mips161.o \
./kern/compile/ASST3/.depend.clock.o \
./kern/compile/ASST3/.depend.cmpdi2.o \
./kern/compile/ASST3/.depend.con_lser.o \
./kern/compile/ASST3/.depend.console.o \
./kern/compile/ASST3/.depend.copyinout.o \
./kern/compile/ASST3/.depend.cpu.o \
./kern/compile/ASST3/.depend.device.o \
./kern/compile/ASST3/.depend.devnull.o \
./kern/compile/ASST3/.depend.divdi3.o \
./kern/compile/ASST3/.depend.emu.o \
./kern/compile/ASST3/.depend.emu_att.o \
./kern/compile/ASST3/.depend.exception-mips1.o \
./kern/compile/ASST3/.depend.file_syscalls.o \
./kern/compile/ASST3/.depend.fstest.o \
./kern/compile/ASST3/.depend.hmacunit.o \
./kern/compile/ASST3/.depend.iordi3.o \
./kern/compile/ASST3/.depend.kgets.o \
./kern/compile/ASST3/.depend.kmalloc.o \
./kern/compile/ASST3/.depend.kmalloctest.o \
./kern/compile/ASST3/.depend.kprintf.o \
./kern/compile/ASST3/.depend.lamebus.o \
./kern/compile/ASST3/.depend.lamebus_machdep.o \
./kern/compile/ASST3/.depend.lhd.o \
./kern/compile/ASST3/.depend.lhd_att.o \
./kern/compile/ASST3/.depend.lib.o \
./kern/compile/ASST3/.depend.loadelf.o \
./kern/compile/ASST3/.depend.lrandom.o \
./kern/compile/ASST3/.depend.lrandom_att.o \
./kern/compile/ASST3/.depend.lser.o \
./kern/compile/ASST3/.depend.lser_att.o \
./kern/compile/ASST3/.depend.lshldi3.o \
./kern/compile/ASST3/.depend.lshrdi3.o \
./kern/compile/ASST3/.depend.ltimer.o \
./kern/compile/ASST3/.depend.ltimer_att.o \
./kern/compile/ASST3/.depend.ltrace.o \
./kern/compile/ASST3/.depend.ltrace_att.o \
./kern/compile/ASST3/.depend.main.o \
./kern/compile/ASST3/.depend.memcpy.o \
./kern/compile/ASST3/.depend.memmove.o \
./kern/compile/ASST3/.depend.memset.o \
./kern/compile/ASST3/.depend.menu.o \
./kern/compile/ASST3/.depend.misc.o \
./kern/compile/ASST3/.depend.moddi3.o \
./kern/compile/ASST3/.depend.muldi3.o \
./kern/compile/ASST3/.depend.myvm.o \
./kern/compile/ASST3/.depend.negdi2.o \
./kern/compile/ASST3/.depend.notdi2.o \
./kern/compile/ASST3/.depend.proc.o \
./kern/compile/ASST3/.depend.proc_syscalls.o \
./kern/compile/ASST3/.depend.qdivrem.o \
./kern/compile/ASST3/.depend.ram.o \
./kern/compile/ASST3/.depend.random.o \
./kern/compile/ASST3/.depend.random_lrandom.o \
./kern/compile/ASST3/.depend.rtclock.o \
./kern/compile/ASST3/.depend.rtclock_ltimer.o \
./kern/compile/ASST3/.depend.runprogram.o \
./kern/compile/ASST3/.depend.rwtest.o \
./kern/compile/ASST3/.depend.secure.o \
./kern/compile/ASST3/.depend.semfs_fsops.o \
./kern/compile/ASST3/.depend.semfs_obj.o \
./kern/compile/ASST3/.depend.semfs_vnops.o \
./kern/compile/ASST3/.depend.semunit.o \
./kern/compile/ASST3/.depend.setjmp.o \
./kern/compile/ASST3/.depend.sfs_balloc.o \
./kern/compile/ASST3/.depend.sfs_bmap.o \
./kern/compile/ASST3/.depend.sfs_dir.o \
./kern/compile/ASST3/.depend.sfs_fsops.o \
./kern/compile/ASST3/.depend.sfs_inode.o \
./kern/compile/ASST3/.depend.sfs_io.o \
./kern/compile/ASST3/.depend.sfs_vnops.o \
./kern/compile/ASST3/.depend.sha256.o \
./kern/compile/ASST3/.depend.snprintf.o \
./kern/compile/ASST3/.depend.spinlock.o \
./kern/compile/ASST3/.depend.spl.o \
./kern/compile/ASST3/.depend.start.o \
./kern/compile/ASST3/.depend.strcat.o \
./kern/compile/ASST3/.depend.strchr.o \
./kern/compile/ASST3/.depend.strcmp.o \
./kern/compile/ASST3/.depend.strcpy.o \
./kern/compile/ASST3/.depend.strlen.o \
./kern/compile/ASST3/.depend.strrchr.o \
./kern/compile/ASST3/.depend.strtok_r.o \
./kern/compile/ASST3/.depend.subdi3.o \
./kern/compile/ASST3/.depend.switch.o \
./kern/compile/ASST3/.depend.switchframe.o \
./kern/compile/ASST3/.depend.synch.o \
./kern/compile/ASST3/.depend.synchtest.o \
./kern/compile/ASST3/.depend.syscall.o \
./kern/compile/ASST3/.depend.test161.o \
./kern/compile/ASST3/.depend.thread.o \
./kern/compile/ASST3/.depend.thread_machdep.o \
./kern/compile/ASST3/.depend.threadlist.o \
./kern/compile/ASST3/.depend.threadlisttest.o \
./kern/compile/ASST3/.depend.threadstart.o \
./kern/compile/ASST3/.depend.threadtest.o \
./kern/compile/ASST3/.depend.time.o \
./kern/compile/ASST3/.depend.time_syscalls.o \
./kern/compile/ASST3/.depend.tlb-mips161.o \
./kern/compile/ASST3/.depend.trap.o \
./kern/compile/ASST3/.depend.tt3.o \
./kern/compile/ASST3/.depend.ucmpdi2.o \
./kern/compile/ASST3/.depend.udivdi3.o \
./kern/compile/ASST3/.depend.uio.o \
./kern/compile/ASST3/.depend.umoddi3.o \
./kern/compile/ASST3/.depend.vfscwd.o \
./kern/compile/ASST3/.depend.vfsfail.o \
./kern/compile/ASST3/.depend.vfslist.o \
./kern/compile/ASST3/.depend.vfslookup.o \
./kern/compile/ASST3/.depend.vfspath.o \
./kern/compile/ASST3/.depend.vnode.o \
./kern/compile/ASST3/.depend.xordi3.o \
./kern/compile/ASST3/autoconf.o \
./kern/compile/ASST3/vers.o 

C_DEPS += \
./kern/compile/ASST3/.depend.__printf.d \
./kern/compile/ASST3/.depend.adddi3.d \
./kern/compile/ASST3/.depend.addrspace.d \
./kern/compile/ASST3/.depend.anddi3.d \
./kern/compile/ASST3/.depend.array.d \
./kern/compile/ASST3/.depend.arraytest.d \
./kern/compile/ASST3/.depend.ashldi3.d \
./kern/compile/ASST3/.depend.ashrdi3.d \
./kern/compile/ASST3/.depend.atoi.d \
./kern/compile/ASST3/.depend.autoconf.d \
./kern/compile/ASST3/.depend.beep.d \
./kern/compile/ASST3/.depend.beep_ltimer.d \
./kern/compile/ASST3/.depend.bitmap.d \
./kern/compile/ASST3/.depend.bitmaptest.d \
./kern/compile/ASST3/.depend.bswap.d \
./kern/compile/ASST3/.depend.bzero.d \
./kern/compile/ASST3/.depend.clock.d \
./kern/compile/ASST3/.depend.cmpdi2.d \
./kern/compile/ASST3/.depend.con_lser.d \
./kern/compile/ASST3/.depend.console.d \
./kern/compile/ASST3/.depend.copyinout.d \
./kern/compile/ASST3/.depend.cpu.d \
./kern/compile/ASST3/.depend.device.d \
./kern/compile/ASST3/.depend.devnull.d \
./kern/compile/ASST3/.depend.divdi3.d \
./kern/compile/ASST3/.depend.emu.d \
./kern/compile/ASST3/.depend.emu_att.d \
./kern/compile/ASST3/.depend.file_syscalls.d \
./kern/compile/ASST3/.depend.fstest.d \
./kern/compile/ASST3/.depend.hmacunit.d \
./kern/compile/ASST3/.depend.iordi3.d \
./kern/compile/ASST3/.depend.kgets.d \
./kern/compile/ASST3/.depend.kmalloc.d \
./kern/compile/ASST3/.depend.kmalloctest.d \
./kern/compile/ASST3/.depend.kprintf.d \
./kern/compile/ASST3/.depend.lamebus.d \
./kern/compile/ASST3/.depend.lamebus_machdep.d \
./kern/compile/ASST3/.depend.lhd.d \
./kern/compile/ASST3/.depend.lhd_att.d \
./kern/compile/ASST3/.depend.lib.d \
./kern/compile/ASST3/.depend.loadelf.d \
./kern/compile/ASST3/.depend.lrandom.d \
./kern/compile/ASST3/.depend.lrandom_att.d \
./kern/compile/ASST3/.depend.lser.d \
./kern/compile/ASST3/.depend.lser_att.d \
./kern/compile/ASST3/.depend.lshldi3.d \
./kern/compile/ASST3/.depend.lshrdi3.d \
./kern/compile/ASST3/.depend.ltimer.d \
./kern/compile/ASST3/.depend.ltimer_att.d \
./kern/compile/ASST3/.depend.ltrace.d \
./kern/compile/ASST3/.depend.ltrace_att.d \
./kern/compile/ASST3/.depend.main.d \
./kern/compile/ASST3/.depend.memcpy.d \
./kern/compile/ASST3/.depend.memmove.d \
./kern/compile/ASST3/.depend.memset.d \
./kern/compile/ASST3/.depend.menu.d \
./kern/compile/ASST3/.depend.misc.d \
./kern/compile/ASST3/.depend.moddi3.d \
./kern/compile/ASST3/.depend.muldi3.d \
./kern/compile/ASST3/.depend.myvm.d \
./kern/compile/ASST3/.depend.negdi2.d \
./kern/compile/ASST3/.depend.notdi2.d \
./kern/compile/ASST3/.depend.proc.d \
./kern/compile/ASST3/.depend.proc_syscalls.d \
./kern/compile/ASST3/.depend.qdivrem.d \
./kern/compile/ASST3/.depend.ram.d \
./kern/compile/ASST3/.depend.random.d \
./kern/compile/ASST3/.depend.random_lrandom.d \
./kern/compile/ASST3/.depend.rtclock.d \
./kern/compile/ASST3/.depend.rtclock_ltimer.d \
./kern/compile/ASST3/.depend.runprogram.d \
./kern/compile/ASST3/.depend.rwtest.d \
./kern/compile/ASST3/.depend.secure.d \
./kern/compile/ASST3/.depend.semfs_fsops.d \
./kern/compile/ASST3/.depend.semfs_obj.d \
./kern/compile/ASST3/.depend.semfs_vnops.d \
./kern/compile/ASST3/.depend.semunit.d \
./kern/compile/ASST3/.depend.sfs_balloc.d \
./kern/compile/ASST3/.depend.sfs_bmap.d \
./kern/compile/ASST3/.depend.sfs_dir.d \
./kern/compile/ASST3/.depend.sfs_fsops.d \
./kern/compile/ASST3/.depend.sfs_inode.d \
./kern/compile/ASST3/.depend.sfs_io.d \
./kern/compile/ASST3/.depend.sfs_vnops.d \
./kern/compile/ASST3/.depend.sha256.d \
./kern/compile/ASST3/.depend.snprintf.d \
./kern/compile/ASST3/.depend.spinlock.d \
./kern/compile/ASST3/.depend.spl.d \
./kern/compile/ASST3/.depend.strcat.d \
./kern/compile/ASST3/.depend.strchr.d \
./kern/compile/ASST3/.depend.strcmp.d \
./kern/compile/ASST3/.depend.strcpy.d \
./kern/compile/ASST3/.depend.strlen.d \
./kern/compile/ASST3/.depend.strrchr.d \
./kern/compile/ASST3/.depend.strtok_r.d \
./kern/compile/ASST3/.depend.subdi3.d \
./kern/compile/ASST3/.depend.switchframe.d \
./kern/compile/ASST3/.depend.synch.d \
./kern/compile/ASST3/.depend.synchtest.d \
./kern/compile/ASST3/.depend.syscall.d \
./kern/compile/ASST3/.depend.test161.d \
./kern/compile/ASST3/.depend.thread.d \
./kern/compile/ASST3/.depend.thread_machdep.d \
./kern/compile/ASST3/.depend.threadlist.d \
./kern/compile/ASST3/.depend.threadlisttest.d \
./kern/compile/ASST3/.depend.threadtest.d \
./kern/compile/ASST3/.depend.time.d \
./kern/compile/ASST3/.depend.time_syscalls.d \
./kern/compile/ASST3/.depend.trap.d \
./kern/compile/ASST3/.depend.tt3.d \
./kern/compile/ASST3/.depend.ucmpdi2.d \
./kern/compile/ASST3/.depend.udivdi3.d \
./kern/compile/ASST3/.depend.uio.d \
./kern/compile/ASST3/.depend.umoddi3.d \
./kern/compile/ASST3/.depend.vfscwd.d \
./kern/compile/ASST3/.depend.vfsfail.d \
./kern/compile/ASST3/.depend.vfslist.d \
./kern/compile/ASST3/.depend.vfslookup.d \
./kern/compile/ASST3/.depend.vfspath.d \
./kern/compile/ASST3/.depend.vnode.d \
./kern/compile/ASST3/.depend.xordi3.d \
./kern/compile/ASST3/autoconf.d \
./kern/compile/ASST3/vers.d 


# Each subdirectory must supply rules for building sources it contributes
kern/compile/ASST3/%.o: ../kern/compile/ASST3/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Compiler'
	gcc -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

kern/compile/ASST3/%.o: ../kern/compile/ASST3/%.S
	@echo 'Building file: $<'
	@echo 'Invoking: Cross GCC Assembler'
	as  -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


